---
author: "https://github.com/jspaaks"
branding:
  color: purple
  icon: check
description: "Validate CITATION.cff and .zenodo.json and check consistency"
inputs:
  DIFF_IGNORE_WHITESPACE:
    default: "1"
    description: "Ignore all whitespace when diffing the expected .zenodo.json with the actual .zenodo.json contents."
    required: false
  FAILURE_EXPECTED:
    default: "0"
    description: "In testing it can be useful to flip the exit codes for failure and success. Set to 1 for flipped definition; 0 or empty gives normal behavior."
    required: false
  WORKDIR:
    default: "."
    description: "The working directory that checks.sh should change to"
    required: false
name: cffconvert
runs:
  args:
    - /bin/sh
    - checks.sh
    - "${{ inputs.WORKDIR }}"
    - "${{ inputs.FAILURE_EXPECTED }}"
    - "${{ inputs.DIFF_IGNORE_WHITESPACE }}"
  image: Dockerfile
  using: docker
