name: cffconvert
author: https://github.com/jspaaks
description: Validate CITATION.cff and .zenodo.json and check consistency
branding:
  icon: check
  color: purple
inputs:
  DIFF_IGNORE_WHITESPACE:
    description: 'Ignore all whitespace when diff'ing the expected .zenodo.json with the actual .zenodo.json contents.'
    required: false
    default: '1'
  FAILURE_EXPECTED:
    description: 'In testing it can be useful to flip the exit codes for failure and success. Set to 1 for flipped definition; 0 or empty gives normal behavior.'
    required: false
    default: '0'
  WORKDIR:
    description: 'The working directory that checks.sh should change to'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - /bin/sh
    - checks.sh
    - ${{ inputs.WORKDIR }}
    - ${{ inputs.FAILURE_EXPECTED }}
    - ${{ inputs.DIFF_IGNORE_WHITESPACE }}
