on: push

jobs:
  build:
    name: "cffconvert"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['==1', '>1.0' , '==1.3.3']
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step references the repository that contains the action.
      - uses: citation-file-format/cffconvert-github-action@tests
        with:
          CFFCONVERT_VERSION: ${{ matrix.version }}
