on: push

jobs:
  build:
    name: "Verify errors"
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step references the directory that contains the action.
      - uses: citation-file-format/cffconvert-github-action@v1
      # various checks
      - name: first
        shell: bash -l {0}
        run: echo "first"
      - name: second
        shell: bash -l {0}
        run: echo "second"
