on: push

jobs:
  build:
    name: "Verify errors"
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      # run the checks on a series of directories
      - uses: citation-file-format/cffconvert-github-action@tests
        with:
          WORKDIR: ''
          FAILURE_EXPECTED: '0'

      - uses: citation-file-format/cffconvert-github-action@tests
        with:
          WORKDIR: non-existing-directory/
          FAILURE_EXPECTED: '1'

      - uses: citation-file-format/cffconvert-github-action@tests
        with:
          WORKDIR: tests/cff-missing/
          FAILURE_EXPECTED: '1'
