name: selftest
on: # on any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:

  no-args:
      runs-on: ubuntu-latest
      steps:
        - name: Clone this repository
          uses: actions/checkout@v2
        - name: Test without any input arguments
          uses: ./
          
  show-help:
      runs-on: ubuntu-latest
      steps:
        - name: Clone this repository
          uses: actions/checkout@v2
        - name: Show help
          uses: ./
          with:
            CFFCONVERT_ARGS: "--help"

  show-version:
      runs-on: ubuntu-latest
      steps:
        - name: Clone this repository
          uses: actions/checkout@v2
        - name: Show version
          uses: ./
          with:
            CFFCONVERT_ARGS: "--version"

  subdirectory:
      runs-on: ubuntu-latest
      steps:
        - name: Clone this repository
          uses: actions/checkout@v2
        - name: tree
          run: tree
        - name: Validate a CITATION.cff in a subdirectory
          uses: ./
          with:
            CFFCONVERT_ARGS: "'--infile'  './tests/subdirectory/CITATION.cff'"
